### ISSUE TITLE
Améliorer la visibilité du titre ; ajouter un calque ? 

### ISSUE THREAD

**Issue by MathildeVrst** [MathildeVrst/Site_HorizonsPhilologie_24#4]

**Comment by Mmellet** [comment]
Proposition de calque : [voir](https://github.com/MathildeVrst/Site_HorizonsPhilologie_24/commit/7cf8ae5e46d07eca84d881c7d8e68ff1db4ae043) 

(j'ai repris la couleur orange)

@MathildeVrst
